apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-serving

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - monitoring/prometheus-k8s.yaml
  - monitoring/grafana-k8s.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: mlops-platform
